version: 2
project_name: tmux-visualiser

before:
  hooks:
    - go test ./src

builds:
  - id: tmux-visualiser
    main: ./src
    binary: tmux-visualiser
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: tmux-visualiser
    repository:
      owner: bma-d
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/bma-d/tmux-visualiser
    description: Live tmux session visualiser for your terminal.
    install: |
      bin.install "tmux-visualiser"
    test: |
      system "#{bin}/tmux-visualiser", "-version"

nfpms:
  - id: tmux-visualiser
    package_name: tmux-visualiser
    homepage: https://github.com/bma-d/tmux-visualiser
    description: Live tmux session visualiser for your terminal.
    maintainer: bma-d
    formats:
      - deb
      - rpm
      - apk

scoops:
  - name: tmux-visualiser
    repository:
      owner: bma-d
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    homepage: https://github.com/bma-d/tmux-visualiser
    description: Live tmux session visualiser for your terminal.
